### ISSUE TITLE
What's the purpose of $puppet::agent::env?

### ISSUE THREAD

**Issue by bschonec** [ghoneycutt/puppet-module-puppet#109]
I don't see that $::env has any value at all.  It's not a facter fact and puppet 'environment' is actually:

[root@ltstd001 puppet]# puppet config print | grep environment
environment = production
[root@ltstd001 puppet]# 

I don't see that $::env works at all for my environment.

**Comment by ghoneycutt** [comment]
It is a variable used by the puppet module. This is a work around when you run puppet initially you are in a given environment though you may bootstrap into another environment. I add the following to hiera

``` yaml
puppet::agent::env: production
```

Or you could create a custom fact, `$::env`, that is set to 'production'
