### ISSUE TITLE
Why is running as a service no longer an option?

### ISSUE THREAD

**Issue by bschonec** [ghoneycutt/puppet-module-puppet#125]
Quoting the README.md:

The agent does not run as a service. There is no good reason for running the service. Instead cron should be used to better manage how and when the agent runs.

Why is cron the better choice?  I've been running the puppet client as a service for years.  Wouldn't it make sense to let the user make the choice as to how to run the client instead of remove that choice entirely?

**Comment by ghoneycutt** [comment]
Hi @bschonec

This is a rewrite of the module for Puppet v4 only and takes on my very opinionated approach. Running through cron allows you to know when the puppet agent will run while still allowing for randomization of the runs. The method for doing this running the service is to use splay, though it does not allow you to know when the agent will run. Why do you run the service other than it being the default?
