### ISSUE TITLE
SRV record support

### ISSUE THREAD

**Issue by anders-larsson** [ghoneycutt/puppet-module-puppet#145]
Hi,

Are there any thoughts about adding support for using SRV records (use_srv_records and srv_domain in puppet.conf)?.

Had a look at the  module and I'm not sure how we would want to implement it in that case. Because we would need to have a way of removing server/ca_server (I suspect(?)) when use_srv_records is enabled and of course the other way around when use_srv_records was used but no longer wanted.

AFAIK this is not possible with ini_settings and we would need to use file_line to remove those lines in that case?

Best regards

**Comment by ghoneycutt** [comment]
Why would ini_settings not work?

**Comment by anders-larsson** [comment]
Ah yes. I guess we could do ensure => absent on the elements we want to get rid off? That's true.Totally forgot about it. Would it be of interest to support SRV records?

How would we want it to work in that case? If use_srv_records is set to true server and ca_server is removed? Or should it still be in the config?

Thanks.

**Comment by ghoneycutt** [comment]
I believe the `custom_settings` allows for the addition of things like SRV support.

https://github.com/ghoneycutt/puppet-module-puppet#custom_settings-type-hash

**Comment by anders-larsson** [comment]
Hello again,

You're correct! It seems to be working fine using custom_settings. It's not possible to remove server/ca_server since the hashes are sent separately to create_resources and attempting to do so ends up with duplicate resources. This could be fixed by merging the hashes before sending the hashes off to create_resources.

However it seems use_srv_records take precedent over server/ca_server. Keeping the values would act as fallback values would I would argue is fine.

Thanks for your help.

**Comment by ghoneycutt** [comment]
No problem. If you need to make the change of how the hashes are merged, I am certainly open to a pull request :)
