### ISSUE TITLE
Add support for manifest ordering for agent

### ISSUE THREAD

**Issue by anthcourtney** [ghoneycutt/puppet-module-puppet#71]
http://puppetlabs.com/blog/introducing-manifest-ordered-resources

The parameter would be ```ordering``` with allowed values being:

* title-hash (the default)
* manifest
* random

**Comment by ghoneycutt** [comment]
I'm declaring bankruptcy on all issues and PR's against this module as I change it to adopt Puppet v4. The master branch will now track that and a legacy branch 'puppetv3' will exist for people still running Puppet v3. I appreciate your work and involvement and hope this ultimately gets us all in a better place with regards to managing our Puppet infrastructure.
